services:
  postgres:
    image: postgres
    container_name: zeta_db
    restart: always
    user: postgres
    secrets:
      - postgres-password
    volumes: [db-data:/var/lib/postgresql/data]
    environment:
      - POSTGRES_DB=bot
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  app:
    container_name: zeta_bot
    build: "."
    secrets:
    - postgres-password
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db-data:

secrets:
  postgres-password:
    file: db.pass